item.2 = sea_lantern
item.3 = shroomlight
item.4 = glowstone
item.6 = magma_block
item.19 = torch
item.21 = soul_torch
item.22 = soul_lantern
item.23 = lantern
item.32 = redstone_torch
item.75 = copper_torch
item.87 = trim_amethyst trim_copper trim_diamond trim_emerald trim_gold trim_iron trim_lapis trim_netherite trim_quartz trim_redstone trim_resin
