iris.features.required = SSBO CUSTOM_IMAGES

screen.columns = 1
screen = [RCGI] [VOXELIZATION] [ATMOSPHERE] [LIGHTING] [MISC]

screen.RCGI = RC_LAYER_COUNT RC_CASCADE_RES RC_INTERVAL_SIZE RC_INTERVAL_OVERLAP RC_VOXEL_ARRAY_SIZE RC_PROBE_ATTEMPTS RC_ADD_PROBES
screen.VOXELIZATION = TRIANGLE_ARRAY_SIZE VOXELIZATION_DISTANCE VOXEL_ARRAY_SIZE VOXEL_PROBE_ATTEMPTS <empty> <empty> VOXELIZE_ENTITIES VOXELIZE_BLOCK_ENTITIES VOXELIZE_PLAYER VOXELIZE_ITEMS
screen.ATMOSPHERE.columns = 2
screen.ATMOSPHERE = ATMOS_BASE_ALTITUDE ATMOS_HEIGHT_SCALE AIR_DENSITY AEROSOL_DENSITY OZONE_DENSITY ATMOS_GROUND_ALBEDO ATMOS_SKY_STEPS ATMOS_TLUT_STEPS ATMOS_MS_DIRECTIONS ATMOS_MS_STEPS AERIAL_STEPS AERIAL_PERSPECTIVE_SCALE SUN_SIZE_MULT MOON_SIZE_MULT MOON_BRIGHTNESS NIGHT_SKY_BRIGHTNESS AIRGLOW_ZENITH ATMOS_UNIT_SCALE AUTO_EXPOSURE AUTO_EXPOSURE_MIN
screen.LIGHTING = SUN_SHADOW_SAMPLES SPECULAR_STRENGTH GI_STRENGTH GI_SKY_STRENGTH GI_SUN_BOUNCE EXPOSURE
screen.MISC = NORMAL_MAPPING SHADOW_SOFTNESS EMISSION_BRIGHTNESS DEBUG_VIEW

sliders = RC_LAYER_COUNT RC_CASCADE_RES RC_INTERVAL_SIZE RC_INTERVAL_OVERLAP RC_VOXEL_ARRAY_SIZE RC_PROBE_ATTEMPTS TRIANGLE_ARRAY_SIZE VOXELIZATION_DISTANCE VOXEL_ARRAY_SIZE VOXEL_PROBE_ATTEMPTS ATMOS_BASE_ALTITUDE ATMOS_HEIGHT_SCALE AIR_DENSITY AEROSOL_DENSITY OZONE_DENSITY ATMOS_GROUND_ALBEDO ATMOS_SKY_STEPS ATMOS_TLUT_STEPS ATMOS_MS_DIRECTIONS ATMOS_MS_STEPS AERIAL_STEPS AERIAL_PERSPECTIVE_SCALE SUN_SIZE_MULT MOON_SIZE_MULT MOON_BRIGHTNESS NIGHT_SKY_BRIGHTNESS AIRGLOW_ZENITH ATMOS_UNIT_SCALE AUTO_EXPOSURE_MIN SUN_SHADOW_SAMPLES SPECULAR_STRENGTH GI_STRENGTH GI_SKY_STRENGTH GI_SUN_BOUNCE EXPOSURE

shadow.enabled = true
shadow.culling = false

#if RC_LAYER_COUNT < 7
    program.deferred2.enabled = false
#endif
#if RC_LAYER_COUNT < 6
    program.deferred3.enabled = false
#endif
#if RC_LAYER_COUNT < 5
    program.deferred4.enabled = false
#endif
#if RC_LAYER_COUNT < 4
    program.deferred5.enabled = false
#endif
#if RC_LAYER_COUNT < 3
    program.deferred6.enabled = false
#endif
#if RC_LAYER_COUNT < 2
    program.deferred7.enabled = false
#endif

#ifdef RC_ADD_PROBES
    program.composite1.enabled = true
#else
    program.composite1.enabled = false
#endif

program.composite2.enabled = false

#if VOXELIZATION_DISTANCE == 32
    image.voxelBufferLod = voxelSamplerLod red_integer r8ui unsigned_byte true false 64 32 32
#elif VOXELIZATION_DISTANCE == 64
    image.voxelBufferLod = voxelSamplerLod red_integer r8ui unsigned_byte true false 128 64 64
#elif VOXELIZATION_DISTANCE == 128
    image.voxelBufferLod = voxelSamplerLod red_integer r8ui unsigned_byte true false 256 96 128
#elif VOXELIZATION_DISTANCE == 192 
    image.voxelBufferLod = voxelSamplerLod red_integer r8ui unsigned_byte true false 384 128 192
#elif VOXELIZATION_DISTANCE == 256 
    image.voxelBufferLod = voxelSamplerLod red_integer r8ui unsigned_byte true false 512 128 256
#else
    image.voxelBufferLod = voxelSamplerLod red_integer r8ui unsigned_byte true false 1024 128 512
#endif

image.transmittanceImg = transmittanceSampler rgba rgba32f float false false 256 64
image.multiScatterImg = multiScatterSampler rgba rgba32f float false false 32 32
image.skyViewImg = skyViewSampler rgba rgba32f float false false 512 256

clouds = on
sun = false
moon = false
stars = false


# triangles  (16 + 48 * TRIANGLE_ARRAY_SIZE)

#if TRIANGLE_ARRAY_SIZE == 1048576
    bufferObject.0 = 50331664
#elif TRIANGLE_ARRAY_SIZE == 2097152
    bufferObject.0 = 100663312
#elif TRIANGLE_ARRAY_SIZE == 3145728
    bufferObject.0 = 150994960
#elif TRIANGLE_ARRAY_SIZE == 4194304
    bufferObject.0 = 201326608
#elif TRIANGLE_ARRAY_SIZE == 8388608
    bufferObject.0 = 402653200
#elif TRIANGLE_ARRAY_SIZE == 16777216
    bufferObject.0 = 805306384
#endif

# texture data
bufferObject.1 = 67117064

#if RC_VOXEL_ARRAY_SIZE == 524288
    bufferObject.2 = 67108864
#elif RC_VOXEL_ARRAY_SIZE == 786432
    bufferObject.2 = 100663296
#elif RC_VOXEL_ARRAY_SIZE == 1048576
    bufferObject.2 = 134217728
#elif RC_VOXEL_ARRAY_SIZE == 1572864
    bufferObject.2 = 201326592
#elif RC_VOXEL_ARRAY_SIZE == 2097152
    bufferObject.2 = 268435456
#elif RC_VOXEL_ARRAY_SIZE == 3145728
    bufferObject.2 = 402653184
#elif RC_VOXEL_ARRAY_SIZE == 4194304
    bufferObject.2 = 536870912
#endif

# voxel data

#if VOXEL_ARRAY_SIZE == 65536
    bufferObject.3 = 524288
#elif VOXEL_ARRAY_SIZE == 1048576
    bufferObject.3 = 8388608
#elif VOXEL_ARRAY_SIZE == 2097152
    bufferObject.3 = 16777216
#elif VOXEL_ARRAY_SIZE == 4194304
    bufferObject.3 = 33554432
#elif VOXEL_ARRAY_SIZE == 8388608
    bufferObject.3 = 67108864
#elif VOXEL_ARRAY_SIZE == 16777216
    bufferObject.3 = 134217728
#endif

bufferObject.4 = 32

texture.composite.shadowtex0 = minecraft:textures/atlas/blocks.png
texture.deferred.shadowtex0 = minecraft:textures/atlas/blocks.png
texture.prepare.shadowtex0 = minecraft:textures/atlas/blocks.png
texture.begin.shadowtex0 = minecraft:textures/atlas/blocks.png

texture.composite.shadowtex1 = minecraft:textures/atlas/blocks_s.png
texture.deferred.shadowtex1 = minecraft:textures/atlas/blocks_s.png
texture.prepare.shadowtex1 = minecraft:textures/atlas/blocks_s.png
texture.begin.shadowtex1 = minecraft:textures/atlas/blocks_s.png

variable.float.voxelOffset_x = ((cameraPositionInt.x % 8 + 8) % 8) + cameraPositionFract.x - 4.0
variable.float.voxelOffset_y = ((cameraPositionInt.y % 8 + 8) % 8) + cameraPositionFract.y - 4.0
variable.float.voxelOffset_z = ((cameraPositionInt.z % 8 + 8) % 8) + cameraPositionFract.z - 4.0

uniform.vec3.voxelOffset = vec3(voxelOffset_x, voxelOffset_y, voxelOffset_z)